version: '3.8'

services:

  server-part-6:
    image: my_fastcgi_server:part_5
    container_name: server-part-6
    tty: true                                         # Определяет, будет ли ассоциирован TTY-терминал с контейнером
    user: root                                        # Устанавливает пользователя по умолчанию внутри контейнера

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy                       # Устанавливает имя контейнера
    depends_on:
      - server-part-6                                 # Указывает, что контейнер nginx-proxy зависит от контейнера server-part-6
    ports:
      - "80:8080"                                     # Пробрасывает порт 80 хоста на порт 8080 контейнера
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro   # Монтирует файл конфигурации nginx.conf в контейнер
    tty: true                                         # Определяет, будет ли ассоциирован TTY-терминал с контейнером
    user: root                                        # Устанавливает пользователя по умолчанию внутри контейнера
